import { ArrowLeftIcon } from "@heroicons/react/outline";
import { doc, onSnapshot } from "firebase/firestore";
import { getProviders, getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Feed from "../components/Feed";
import Login from "../components/Login";
import Posts from "../components/Posts";
import Sidebar from "../components/Sidebar";
import { db } from "../firebase";
const initialState = {
  text: "",
};
function PostPage({ providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [post, setPost] = useState();
  const router = useRouter();
  const [state, setState] = useState(initialState);
  const [data, setData] = useState();
  const { id } = router.query;

  useEffect(
    () =>
      onSnapshot(doc(db, "posts", id), (snapshot) => {
        setPost(snapshot.data());
      }),
    [db]
  );

  // useEffect(() => {
  //   if (id) {
  //     setState({ ...data[id] });
  //   } else {
  //     setState({ ...initialState });
  //   }
  // }, [id, db]);

  if (!session) return <Login providers={providers} />;
  return (
    <div className="">
      <Head>
        <title>
          {post?.username} on Twitter: "{post?.text}"
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <div className="flex-grow border-l border-r border-gray-700 max-w-2xl sm:ml-[73px] xl:ml-[370px]">
          <div className="flex items-center mr-2  justify-between px-[1.5] py-2 border-b border-gray-700 text-[#d9d9d9] font-semibold text-xl gap-x-4 sticky top-0 z-50 bg-black">
            <div
              className="hoverAnimation w-9 h-9 flex items-center justify-center xl:px-0"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5 text-white  " />
            </div>
            <div>
              <button
                className="bg-[#00bcd4] text-white rounded-full px-4 py-1.5  mr-2 hover:bg-[#1a8cd8]"
                onClick={() => router.push("/")}
              >
                Edit
              </button>
            </div>
          </div>
          <Posts id={id} post={post} postPage />
        </div>
      </main>
    </div>
  );
}

export default PostPage;

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}
